name: Test

on: [ push, pull_request ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # colab runs on 3.7, 3.9 is the latest published version
        python-version: [ '3.7', '3.8', '3.9' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.2.2
          $HOME/.local/bin/poetry config virtualenvs.in-project true
      - uses: actions/cache@v3
        with:
          path: .venv
          key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
          #restore-keys: |
          #  poetry-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Install depencies
        run: $HOME/.local/bin/poetry install -E alphafold
      - name: Run tests
        run: .venv/bin/pytest
      - name: Run CLI
        run: |
          .venv/bin/colabfold_batch --help
          .venv/bin/colabfold_search --help
          .venv/bin/colabfold_split_msas --help

